name: Build

on:
  workflow_call:
    inputs:
      os_list:
        description: "JSON list of OS"
        required: false
        type: string
        default: "['windows-latest']"

jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os_list) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup python packages
        run: |
          pip install pipx
          pipx ensurepath
          pipx install commitizen
          pipx upgrade commitizen

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install node dependencies
        run: |
          npm ci

      - name: Install wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install nsis (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install nsis -y

      - name: Add nsis to PATH (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "C:\Program Files (x86)\NSIS" >> $env:GITHUB_PATH

      - name: Check nsis (Windows)
        if: runner.os == 'Windows'
        run: |
          makensis -VERSION

      - name: Build binary
        shell: pwsh
        run: |
          ./scripts/build.ps1

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: "./build/bin/agent-smith-tray-amd64-installer.exe"
